[package]
name = "rskynet-examples"
description = "rskynet 的统一示例应用"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[dependencies]
rskynet = { path = "../crates/rskynet", features = ["cluster", "dashboard", "websocket"] }
prost = { workspace = true }
