[package]
name = "rskynet-timer"
description = "rskynet 的定时器：分层时间轮加一条独占线程的定时器服务"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
rskynet-core = { workspace = true }

crossbeam-queue = { workspace = true }
serde = { workspace = true }
